name: Deploy to EC2 (self-hosted runner)

on:
  push:
    branches: [ "main" ]

concurrency:
  group: rein-weather-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, ec2-prod]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make release name
        id: rel
        run: echo "REL=$(date +%Y-%m-%d_%H%M%S)" >> $GITHUB_OUTPUT

      - name: Prepare release dir
        run: |
          set -euo pipefail
          BASE=/home/ubuntu
          RDIR=$BASE/releases/${{ steps.rel.outputs.REL }}
          mkdir -p "$RDIR"
          # ワークスペースの中身を丸ごとコピー（VCS情報は除外）
          rsync -a --delete --exclude=".git" . "$RDIR/"

      - name: Build venv & deps
        run: |
          set -euo pipefail
          BASE=/home/ubuntu
          RDIR=$BASE/releases/${{ steps.rel.outputs.REL }}
          cd "$RDIR"
          python3 -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt
          ./venv/bin/pip install gunicorn
          # .env を前版から継承（Actionsには載せない）
          if [ -f /home/ubuntu/.app_env ]; then cp /home/ubuntu/.app_env "$RDIR/.env"; fi

      - name: Smoke test on 8000
        run: |
          set -euo pipefail
          BASE=/home/ubuntu
          RDIR=$BASE/releases/${{ steps.rel.outputs.REL }}
          cd "$RDIR"
          ./venv/bin/gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app --bind 127.0.0.1:8000 &
          GPID=$!
          sleep 2
          curl -fsS http://127.0.0.1:8000/health
          kill $GPID

      - name: Switch weather-app-clean & restart service
        run: |
          set -euo pipefail
          BASE=/home/ubuntu
          RDIR=$BASE/releases/${{ steps.rel.outputs.REL }}
          ln -sfn "$RDIR" $BASE/weather-app-clean
          sudo systemctl restart weather.service
          # 古いリリースは5世代だけ残して掃除
          ls -dt $BASE/releases/* | tail -n +6 | xargs -r rm -rf
